- name: Copy repo file
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: Install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: Start Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: create prometheus datasource
  community.grafana.grafana_datasource:
    name: prometheus
    ds_type: prometheus
    ds_url: http://prometheus-internal.sdevopsp25.site:9090
    access: proxy
    url: http://localhost:3000
    url_username: admin
    url_password: admin123

- name: Copy json to tmp
  ansible.builtin.copy:
    src: dashboard.json
    dest: /tmp/dashboard.json

- name: Import Grafana dashboard foo
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    url_username: admin
    url_password: admin123
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: /tmp/dashboard.json
