labels:
  - tag_Name
  - tag_Env
  - tag_Component
  - instance_type
  - instance_id

secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=infra-secrets/data/prometheus token={{vault_token}} url=https://vault.sdevopsp25.site:8200 validate_certs=false') }}"