route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: "email"
    email_configs:
      - to: "shubhpatil990@gmail.com"
        from: "shubhpatil990@gmail.com"
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "{{secrets.smtp_username}}"
        auth_password: "{{secrets.smtp_password}}"
        require_tls: true